
target 'TestAll' do
  
    #pod 'Masonry'
    #pod 'SDAutoLayout', '~> 2.1.3'
    #pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
    
    #pod 'RealReachability’   #常用另一个框架 Reachability
    #pod 'AFNetworking', '~> 3.0'
    #pod 'HYBNetworking', '~> 3.3.1' #包括afn3.1.0
    #pod 'MJRefresh'
    
    #pod 'SDWebImage', '~> 4.0'
    #pod 'BlocksKit'
    #pod 'KVOController'
    #pod 'MBProgressHUD', '~> 1.1.0'
    #pod 'IQKeyboardManager' #iOS8 and later
    
    #pod 'TZImagePickerController’ #4.3k star
    #pod 'ZLPhotoBrowser' #1.7k star
    #pod 'SDCycleScrollView','~> 1.75' #图片文字轮播
    #pod 'WMPlayer','3.0.6' #包含Masonry (1.1.0)
    #pod 'ZFPlayer'
    #pod 'KSPhotoBrowser' 

    #pod 'MJExtension'
    #pod 'Realm'
    #pod 'ReactiveObjC', '~> 3.1.0' 

    #pod 'JPush', '3.0.2'

end
